remote_id = '102048694'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = []

[options]
remote-menubar-drag-right = '1.0'
theme = 'dark'
remote-menubar-drag-left = '0.0'

[ui_flutter]
wm_Main = '{"width":935.0,"height":1003.0,"offsetWidth":20.0,"offsetHeight":57.0,"isMaximized":true,"isFullscreen":false}'
wm_RemoteDesktop = '{"width":1920.0,"height":1080.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":false}'
peer-sorting = 'Remote ID'
